name: Rust-Monitor

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev    

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Linux Release
      id: linux_release
      uses: actions-rs/cargo@v1
      with:
        command: build 
        args: --verbose --release --target=x86_64-unknown-linux-gnu

    - name: Create tar.gz
      run: tar -czvf rust-monitor-linux.tar.gz -C ./target/x86_64-unknown-linux-gnu/release .

    - name: Upload to Workflow Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: rust-monitor-linux
        path: ./rust-monitor-linux.tar.gz     

